const db = connect('localhost/squirreldata');

db.squirrels.insertMany([
    { squirrel_id: 1, time: 'AM', date: 10012023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Library', above_ground: true},
    { squirrel_id: 2, time: 'AM', date: 10012023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'White', nearby_building: 'Ingersoll Hall', above_ground: false},
    { squirrel_id: 3, time: 'PM', date: 10022023, age: 'Adult', primary_fur_color: 'Black', highlight_fur_color: '', nearby_building: 'Boylan Hall', above_ground: true},
    { squirrel_id: 4, time: 'AM', date: 10032023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: false},
    { squirrel_id: 5, time: 'AM', date: 10032023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 6, time: 'PM', date: 10042023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'Black', nearby_building: 'Boylan Hall', above_ground: true},
    { squirrel_id: 7, time: 'AM', date: 10052023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: '', nearby_building: '', above_ground: false},
    { squirrel_id: 8, time: 'PM', date: 10052023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 9, time: 'PM', date: 10052023, age: 'Adult', primary_fur_color: 'Black', highlight_fur_color: '', nearby_building: 'Whitehead Hall', above_ground: false},
    { squirrel_id: 10, time: 'AM', date: 10062023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Ingersoll Hall', above_ground: false},
    { squirrel_id: 11, time: 'PM', date: 10062023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: '', above_ground: false},
    { squirrel_id: 12, time: 'AM', date: 10072023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: 'Ingersoll Hall', above_ground: false},
    { squirrel_id: 13, time: 'PM', date: 10072023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Topfer Library Cafe', above_ground: false},
    { squirrel_id: 14, time: 'AM', date: 10082023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Library', above_ground: true},
    { squirrel_id: 15, time: 'AM', date: 10082023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: 'Whitehead Hall', above_ground: false},
    { squirrel_id: 16, time: 'PM', date: 10082023, age: '', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: 'Ingersoll Hall Extension', above_ground: false},
    { squirrel_id: 17, time: 'AM', date: 10092023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Whiteman Hall', above_ground: false},
    { squirrel_id: 18, time: 'PM', date: 10092023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: '', above_ground: true},
    { squirrel_id: 19, time: 'PM', date: 10092023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Boylan Hall', above_ground: true},
    { squirrel_id: 20, time: 'AM', date: 10102023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: false},
    { squirrel_id: 21, time: 'AM', date: 10112023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: '', above_ground: false},
    { squirrel_id: 22, time: 'PM', date: 10112023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: '', above_ground: false},
    { squirrel_id: 23, time: 'AM', date: 10122023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: 'Ingersoll Hall Extension', above_ground: false},
    { squirrel_id: 24, time: 'AM', date: 10122023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: true},
    { squirrel_id: 25, time: 'PM', date: 10122023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Topfer Library Cafe', above_ground: true},
    { squirrel_id: 26, time: 'PM', date: 10122023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Ingersoll Hall', above_ground: false},
    { squirrel_id: 27, time: 'PM', date: 10122023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 28, time: 'AM', date: 10132023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Whitehead Hall', above_ground: true},
    { squirrel_id: 29, time: 'PM', date: 10132023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: 'Boylan Hall', above_ground: false},
    { squirrel_id: 30, time: 'AM', date: 10142023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: '', above_ground: true},
    { squirrel_id: 31, time: 'AM', date: 10142023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Whitehead Hall', above_ground: true},
    { squirrel_id: 32, time: 'PM', date: 10142023, age: '', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Boylan Hall', above_ground: false},
    { squirrel_id: 33, time: 'PM', date: 10142023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'Gray', nearby_building: 'Ingersoll Hall', above_ground: false},
    { squirrel_id: 34, time: 'PM', date: 10142023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Boylan Hall', above_ground: false},
    { squirrel_id: 35, time: 'AM', date: 10152023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: 'Whiteman Hall', above_ground: true},
    { squirrel_id: 36, time: 'AM', date: 10152023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: '', above_ground: true},
    { squirrel_id: 37, time: 'PM', date: 10152023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: 'Ingersoll Hall Extension', above_ground: true},
    { squirrel_id: 38, time: 'AM', date: 10162023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Black', nearby_building: '', above_ground: false},
    { squirrel_id: 39, time: 'AM', date: 10162023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Whitehead Hall', above_ground: false},
    { squirrel_id: 40, time: 'PM', date: 10162023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Ingersoll Hall Extension', above_ground: true},
    { squirrel_id: 41, time: 'PM', date: 10162023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 42, time: 'PM', date: 10162023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Whitehead Hall', above_ground: false},
    { squirrel_id: 43, time: 'AM', date: 10172023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: '', nearby_building: 'Ingersoll Hall', above_ground: false},
    { squirrel_id: 44, time: 'PM', date: 10172023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: '', above_ground: false},
    { squirrel_id: 45, time: 'PM', date: 10172023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Boylan Hall', above_ground: true},
    { squirrel_id: 46, time: 'AM', date: 10182023, age: '', primary_fur_color: 'Cinnamon', highlight_fur_color: '', nearby_building: '', above_ground: true},
    { squirrel_id: 47, time: 'AM', date: 10182023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Library', above_ground: true},
    { squirrel_id: 48, time: 'PM', date: 10182023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Library', above_ground: true},
    { squirrel_id: 49, time: 'AM', date: 10192023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: '', above_ground: false},
    { squirrel_id: 50, time: 'AM', date: 10192023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Whitehead Hall', above_ground: false},
    { squirrel_id: 51, time: 'PM', date: 10192023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: '', above_ground: false},
    { squirrel_id: 52, time: 'PM', date: 10192023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: '', nearby_building: 'Whitehead Hall', above_ground: true},
    { squirrel_id: 53, time: 'PM', date: 10192023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Ingersoll Hall Extension', above_ground: true},
    { squirrel_id: 54, time: 'AM', date: 10202023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Black', nearby_building: 'Ingersoll Hall', above_ground: true},
    { squirrel_id: 55, time: 'AM', date: 10202023, age: '', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Boylan Hall', above_ground: false},
    { squirrel_id: 56, time: 'AM', date: 10202023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: '', above_ground: false},
    { squirrel_id: 57, time: 'PM', date: 10202023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Boylan Hall', above_ground: false},
    { squirrel_id: 58, time: 'PM', date: 10202023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: '', above_ground: true},
    { squirrel_id: 59, time: 'PM', date: 10202023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Ingersoll Hall Extension', above_ground: false},
    { squirrel_id: 60, time: 'PM', date: 10202023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 61, time: 'AM', date: 10212023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Ingersoll Hall', above_ground: true},
    { squirrel_id: 62, time: 'AM', date: 10212023, age: 'Juvenile', primary_fur_color: 'Black', highlight_fur_color: 'Gray', nearby_building: 'Ingersoll Hall', above_ground: false},
    { squirrel_id: 63, time: 'PM', date: 10212023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Boylan Hall', above_ground: false},
    { squirrel_id: 64, time: 'PM', date: 10212023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: false},
    { squirrel_id: 65, time: 'AM', date: 10222023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: '', above_ground: false},
    { squirrel_id: 66, time: 'PM', date: 10222023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: '', nearby_building: 'Library', above_ground: true},
    { squirrel_id: 67, time: 'AM', date: 10232023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Topfer Library Cafe', above_ground: true},
    { squirrel_id: 68, time: 'AM', date: 10232023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Whiteman Hall', above_ground: true},
    { squirrel_id: 69, time: 'PM', date: 10232023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Ingersoll Hall Extension', above_ground: false},
    { squirrel_id: 70, time: 'PM', date: 10232023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: '', above_ground: false},
    { squirrel_id: 71, time: 'AM', date: 10242023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: false},
    { squirrel_id: 72, time: 'AM', date: 10242023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Ingersoll Hall', above_ground: true},
    { squirrel_id: 73, time: 'PM', date: 10242023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: true},
    { squirrel_id: 74, time: 'PM', date: 10242023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Boylan Hall', above_ground: false},
    { squirrel_id: 75, time: 'PM', date: 10242023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Ingersoll Hall', above_ground: false},
    { squirrel_id: 76, time: 'AM', date: 10252023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: '', above_ground: true},
    { squirrel_id: 77, time: 'AM', date: 10252023, age: '', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Ingersoll Hall Extension', above_ground: true},
    { squirrel_id: 78, time: 'AM', date: 10252023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Ingersoll Hall', above_ground: true},
    { squirrel_id: 79, time: 'PM', date: 10252023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: '', above_ground: false},
    { squirrel_id: 80, time: 'PM', date: 10252023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 81, time: 'PM', date: 10252023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: '', above_ground: true},
    { squirrel_id: 82, time: 'PM', date: 10252023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: '', above_ground: false},
    { squirrel_id: 83, time: 'AM', date: 10262023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Whiteman Hall', above_ground: true},
    { squirrel_id: 84, time: 'AM', date: 10262023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Topfer Library Cafe', above_ground: true},
    { squirrel_id: 85, time: 'PM', date: 10262023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 86, time: 'PM', date: 10262023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: false},
    { squirrel_id: 87, time: 'AM', date: 10272023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'White', nearby_building: '', above_ground: false},
    { squirrel_id: 88, time: 'AM', date: 10272023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Whitehead Hall', above_ground: true},
    { squirrel_id: 89, time: 'PM', date: 10272023, age: '', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: true},
    { squirrel_id: 90, time: 'PM', date: 10272023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Library', above_ground: true},
    { squirrel_id: 91, time: 'AM', date: 10282023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Whiteman Hall', above_ground: false},
    { squirrel_id: 92, time: 'AM', date: 10282023, age: 'Adult', primary_fur_color: 'Black', highlight_fur_color: 'Gray', nearby_building: 'Whitehead Hall', above_ground: false},
    { squirrel_id: 93, time: 'PM', date: 10282023, age: 'Juvenile', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: '', above_ground: true},
    { squirrel_id: 94, time: 'PM', date: 10282023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Boylan Hall', above_ground: true},
    { squirrel_id: 95, time: 'PM', date: 10282023, age: 'Adult', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: '', above_ground: false},
    { squirrel_id: 96, time: 'AM', date: 10292023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: '', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 97, time: 'PM', date: 10292023, age: 'Juvenile', primary_fur_color: 'Gray', highlight_fur_color: 'Cinnamon', nearby_building: 'Library', above_ground: false},
    { squirrel_id: 98, time: 'AM', date: 10302023, age: '', primary_fur_color: 'Gray', highlight_fur_color: 'White', nearby_building: 'Ingersoll Hall Extension', above_ground: true},
    { squirrel_id: 99, time: 'PM', date: 10302023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: '', nearby_building: '', above_ground: true},
    { squirrel_id: 100, time: 'AM', date: 10312023, age: 'Adult', primary_fur_color: 'Cinnamon', highlight_fur_color: 'Gray', nearby_building: 'Library', above_ground: false}
])
